version: 6.0.0.{build}

dotnet_csproj:
  version_prefix: '6.0.0'
  patch: true
  file: 'src\**\*.csproj'

configuration: Release

image: Visual Studio 2019

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

skip_tags: true

nuget:
  disable_publish_on_pr: true

clone_depth: 1

test: off

build_script:
- ps: .\build.ps1

deploy:
- provider: NuGet
  server: https://www.myget.org/F/autofac/api/v2/package
  api_key:
    secure: rCUEY75fXN0wxtMy6QL4jCrLdaYbxIBzIXWeN+wEu/XDpyqimzreOc5AH5jMd5ah
  symbol_server: https://www.myget.org/F/autofac/symbols/api/v2/package
