image: Visual Studio 2022

version: "6.1.0.{build}"

dotnet_csproj:
  version_prefix: "6.1.0"
  patch: true
  file: 'src\**\*.csproj'

configuration: Release

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

install:
  - ps: |
        $path = [Environment]::GetEnvironmentVariable("path", "machine")
        $newPath = ($path.Split(';') | Where-Object { $_ -eq 'C:\ProgramData\chocolatey\bin' }) -join ';'
        [Environment]::SetEnvironmentVariable("path", $newPath, "machine")
  - cmd: appveyor-retry choco install gpg4win

skip_tags: true

nuget:
  disable_publish_on_pr: true

clone_depth: 1

test: false

build_script:
  - pwsh: .\build.ps1

artifacts:
  - path: artifacts\packages\**\*.*nupkg
    name: MyGet
    type: NuGetPackage

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/autofac/api/v2/package
    symbol_server: https://www.myget.org/F/autofac/api/v2/package
    api_key:
      secure: xUXExgVAagrdEicCjSxsQVrwiLo2TtnfqMbYB9Cauq2cpbm/EVz957PBK0v/GEYq
    artifact: MyGet
